FROM ubuntu:20.04

# 解决中文乱码问题
ENV LANG C.UTF-8
ENV LC_CTYPE=C.UTF-8


RUN apt update && apt install ca-certificates -y

COPY ./sources.list /etc/apt/sources.list

RUN cat /etc/apt/sources.list
RUN rm -rf /var/lib/apt/lists/*

RUN apt-get update
RUN apt update
RUN apt install tzdata -y
RUN apt install python3 -y
RUN apt install nodejs -y
RUN apt install golang -y
RUN apt install openjdk-17-jdk -y


# 添加时区环境变量，亚洲，上海
ENV TimeZone=Asia/Shanghai
# 使用软连接，并且将时区配置覆盖/etc/timezone
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime
RUN echo $TimeZone > /etc/timezone






